name: learnup
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

#dependencies:
#  flutter:
#    sdk: flutter
#  cupertino_icons: ^1.0.8
#  firebase_core: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^5.3.1
  flutter_lints: ^4.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  cloud_firestore: ^5.4.4
  charts_flutter: ^0.12.0
  google_fonts: ^4.0.0
  image_picker: ^1.1.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6


flutter:
  uses-material-design: true


#flutter:
#  uses-material-design: true

