// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuwr6ts8yT-qnfuE7aF8EF6QHy-ehYCbY',
    appId: '1:851637919397:web:f2d0da481e5d6450b7f74c',
    messagingSenderId: '851637919397',
    projectId: 'learnup-d6574',
    authDomain: 'learnup-d6574.firebaseapp.com',
    storageBucket: 'learnup-d6574.appspot.com',
    measurementId: 'G-Z2C17D0PWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUKNLOiT636-knc7ztvGzp0OagFgeVB7w',
    appId: '1:851637919397:android:6a90c897a1f448b2b7f74c',
    messagingSenderId: '851637919397',
    projectId: 'learnup-d6574',
    storageBucket: 'learnup-d6574.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfHstiXRwCOMxOLIt96yC0_LJvQZpAi60',
    appId: '1:851637919397:ios:499f85b33a2282b5b7f74c',
    messagingSenderId: '851637919397',
    projectId: 'learnup-d6574',
    storageBucket: 'learnup-d6574.appspot.com',
    iosBundleId: 'com.example.learnup',
  );
}
